services:
  # PostgreSQL Database
  postgres:
    image: postgres:18-alpine
    container_name: medusa_postgres_mytest
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa-store-mytest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_mytest:/var/lib/postgresql/data
    networks:
      - medusa_network_mytest

  # Redis
  redis:
    image: redis:7-alpine
    container_name: medusa_redis_mytest
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - medusa_network_mytest

  # Medusa Server
  # This service runs the Medusa backend application
  # and the admin dashboard.
  medusa:
    build: .
    container_name: medusa_backend_mytest
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/medusa-store-mytest
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    volumes:
      - .:/server
      - /server/node_modules
    networks:
      - medusa_network_mytest

volumes:
  postgres_data_mytest:

networks:
  medusa_network_mytest:
    driver: bridge
